#!/usr/bin/env python
# 
# GPLv3 2011-2012 by anonymous
# 

import igraph, math, csv, time
from sys import argv, exit
from os import listdir, path, environ, closerange
from jinja2 import Template, Environment, FileSystemLoader
from optparse import OptionParser
from datetime import datetime
from collections import defaultdict

try:
    from collections import Counter
except ImportError:
    print "ERR: please use python >= 2.7"
    exit(1)

environ['TZ'] = 'UTC'
time.tzset()

parser = OptionParser()
parser.add_option("-g", "--graph", dest="gmlfile",
    help="Single source graph FILE", metavar="FILE")

parser.add_option("-i", "--include", dest="gmllist",
    help="Load all graphs listed in FILE", metavar="FILE")

parser.add_option("-d", "--dest", dest="destdir",
    default=".",
    help="Destination DIR. Default: current dir", 
    metavar="DIR")

parser.add_option("-x", "--index", dest="index",
    default="index.tmpl",
    help="Create index using FILE as template. Default: index.tmpl", 
    metavar="FILE")

parser.add_option("-t", "--tags", dest="tags",
    default="data/tags_edges.list",
    help="Load TAGS from FILE. Default: data/tags_edges.list",
    metavar="FILE")

(options, args) = parser.parse_args()

graph_files = set()
if options.gmlfile:
    graph_files.add(options.gmlfile.strip())

if options.gmllist:
    gfh = open(options.gmllist)
    for gf in gfh.readlines():
        graph_files.add(gf.strip())
    gfh.close()

if len(graph_files) < 1:
    print "No source .gml files"
    exit(1)

if options.tags:
    print "Loading TAGS from %s..." % options.tags
    tags = defaultdict(list)
    for k,v in [ (l.split() ) for l in open(options.tags).readlines() ]:
        tags[k].append(v)

def format_timestamp(ts, tsformat = '%Y-%m-%d'):
    d = datetime.fromtimestamp(float(ts))
    return d.strftime(tsformat)

def get_tags(labels):
    tmp_tags = set()
    for label in labels:
        if label in tags:
            for tag in tags[label]:
                tmp_tags.add(tag)

    return tmp_tags

CURDIR = path.dirname(path.abspath(__file__))
env = Environment(loader=FileSystemLoader(CURDIR))
env.filters['formatts'] = format_timestamp

# load index template
index_tmpl = env.get_template(options.index)
index = list()

for gml in graph_files:
    # load graph from file
    g = igraph.load(gml)

    if options.tags:
        graph_tags = get_tags(g.vs['label'])
    else:
        graph_tags = []

    if 'classification' in g.vs.attribute_names():
        classifications = g.vs['classification']

    if options.index:
        meta = {
            'nodes': g.vcount(),
            'edges': g.ecount(),
            'filename': "%s.html" % path.basename(gml), 
            'tags': graph_tags,
            'diameter': g.diameter(),
            'radius': g.radius()
        }

        # count and manual sort of classifications
        if classifications:
            clf_sort = {
                'UNCLASSIFIED': 0,
                'UNCLASSIFIED//FOR OFFICIAL USE ONLY': 1,
                'CONFIDENTIAL': 2,
                'CONFIDENTIAL//NOFORN': 3,
                'SECRET': 4,
                'SECRET//NOFORN': 5,
                '': 6
            }
            # count
            ccnt = Counter(classifications).items()
            # total
            t = float(len(classifications))
            # percent
            clfp = [ (c, float(cnt) /(t / 100)) for c, cnt in ccnt ]
            # manual sort
            scc = sorted(clfp, key=lambda c: clf_sort[c[0]])
            meta.update({'classification': scc})

        index.append(meta)
    del g

index_file = "%s/index.html" % (options.destdir)
if path.exists(index_file):
    print "Index %s exists. skipping" % index_file
else:
    print "Writing %s" % index_file
    ifh = open(index_file,'w')
    ifh.write(index_tmpl.render(index=sorted(index, reverse=True)))
    ifh.close()

